# Generated by Django 2.0.6 on 2018-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='reply',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='thread',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='thread',
            name='author',
            field=models.CharField(default='MySite User', max_length=80, verbose_name='author'),
        ),
    ]
