# Generated by Django 2.0.6 on 2018-09-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_forum', '0003_auto_20180826_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='n_replies',
            field=models.IntegerField(default=0, verbose_name='n replies'),
        ),
        migrations.AddField(
            model_name='thread',
            name='n_posts',
            field=models.IntegerField(default=0, verbose_name='n posts'),
        ),
    ]
