# Generated by Django 2.0.6 on 2018-09-04 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_forum', '0004_auto_20180904_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='n_replies',
            field=models.IntegerField(default=0, verbose_name='n_replies'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date_replied',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_replied'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='n_posts',
            field=models.IntegerField(default=0, verbose_name='n_posts'),
        ),
    ]
