# Generated by Django 2.0.6 on 2018-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_forum', '0005_auto_20180904_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_posted']},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['date_replied']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['date_created']},
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
    ]
