# Generated by Django 2.0.6 on 2018-07-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site', verbose_name='staff status'),
        ),
    ]
