# Generated by Django 2.0.6 on 2018-07-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_user', '0002_mysiteuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysiteuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether the user should be considered active.Unselect rather than deleting accounts', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='mysiteuser',
            name='name',
            field=models.CharField(default='MySite User', max_length=20, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='mysiteuser',
            name='username',
            field=models.CharField(db_index=True, max_length=80, unique=True, verbose_name='username'),
        ),
    ]
