# Generated by Django 2.0.6 on 2018-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_user', '0005_auto_20180823_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='thread',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
