# Generated by Django 2.0.6 on 2018-08-26 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite_user', '0006_auto_20180823_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysiteuser',
            name='name',
            field=models.CharField(default='MySite User', max_length=80, verbose_name='name'),
        ),
    ]
